Repository UMC-Hackathon-D/Server, pull requests merged in 2024-12, with the labels that each got.

#5 ✨ [Feature] CICD 구축
  .github/workflows/deploy-main.yml
  .idea/.gitignore
  .idea/Server.iml
  .idea/modules.xml
  .idea/vcs.xml
Labels: :sparkles: feature

#16 ✨feat:사용자 재입장 구현
  package-lock.json
  package.json
  prisma/migrations/20241218223248_init_database/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/controllers/user.controller.js
  src/db.config.js
  src/dtos/user.dto.js
  src/index.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#24 🐛 [bug] import 빠진거 채워넣음
  src/services/user.service.js
Labels: :bug: bug

#25 📝 [docs]: 스웨거 설정 변경
  src/index.js
Labels: :memo: docs

#27 ✨[Feature] 낭만모음집 조회
  src/controllers/collection.controller.js
  src/controllers/party.controller.js
  src/dtos/collection.dto.js
  src/error.js
  src/index.js
  src/repositories/collection.repository.js
  src/services/collection.service.js
Labels: :sparkles: feature

#35 ♻️[REFACTOR]파티, 유저 에러 핸들링 추가
  prisma/migrations/migration_lock.toml
  src/dtos/user.dto.js
  src/error.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :recycle: refactor

#39 [FEAT] get user ongoing mission
  src/controllers/mission.controller.js
  src/dtos/mission.dto.js
  src/index.js
  src/mission.error.js
  src/repositories/mission.repository.js
  src/services/mission.service.js
Labels: :sparkles: feature

#62 [Re] 그룹 생성시 에러코드500 변경
  src/errors/party.error.js
Labels: :recycle: refactor

#75 ✨ [Feature] S3 세팅완료
  package-lock.json
  package.json
  src/middleware/s3Setting.js
Labels: :sparkles: feature

#80 ✨[Feature] 미션 후기 수정
  src/controllers/collection.controller.js
  src/dtos/collection.dto.js
  src/index.js
  src/middleware/s3Setting.js
  src/repositories/collection.repository.js
  src/services/collection.service.js
Labels: :sparkles: feature

#82 ✨ [Feature] 미션 후기 삭제기능
  src/controllers/collection.controller.js
  src/dtos/collection.dto.js
  src/index.js
  src/repositories/collection.repository.js
  src/services/collection.service.js
Labels: :sparkles: feature
